/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#000666',
        'on-primary': '#ffffff',
        'surface-container-highest': '#cfe6f2',
        'secondary-container': '#cfe6f2',
        'on-secondary-fixed-variant': '#354a53',
        'background': '#f3faff',
        'on-primary-fixed-variant': '#343d96',
        'on-error': '#ffffff',
        'on-surface-variant': '#454652',
        'inverse-primary': '#bdc2ff',
        'primary-fixed': '#e0e0ff',
        'surface-container-low': '#e6f6ff',
        'surface-container-high': '#d5ecf8',
        'on-error-container': '#93000a',
        'tertiary-container': '#003909',
        'secondary': '#4c616c',
        'surface': '#f3faff',
        'surface-container': '#dbf1fe',
        'on-secondary-fixed': '#071e27',
        'surface-bright': '#f3faff',
        'on-surface': '#071e27',
        'surface-dim': '#c7dde9',
        'tertiary': '#002103',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#a3f69c',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#002204',
        'secondary-fixed': '#cfe6f2',
        'on-secondary-container': '#526772',
        'outline': '#767683',
        'on-tertiary-container': '#5aa958',
        'outline-variant': '#c6c5d4',
        'surface-variant': '#cfe6f2',
        'error': '#ba1a1a',
        'on-primary-container': '#8690ee',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#005312',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#1e333c',
        'on-background': '#071e27',
        'primary-fixed-dim': '#bdc2ff',
        'on-primary-fixed': '#000767',
        'primary-container': '#1a237e',
        'surface-tint': '#4c56af',
        'secondary-fixed-dim': '#b4cad6',
        'inverse-on-surface': '#dff4ff',
        'tertiary-fixed-dim': '#88d982'
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif']
      }
    },
  },
  plugins: [],
}
